# Generated by Django 6.0 on 2025-12-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_remove_profile_user_remove_project_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(null=True, upload_to='profiles/'),
        ),
    ]
