# Generated by Django 5.2.9 on 2025-12-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True # 최초 파일

    dependencies = [ # 마이그레이션 파일 간 의존성
    ]

    operations = [ # 동작 순서 정의
        migrations.CreateModel( # 테이블 생성
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('original_url', models.URLField()),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'short_url',
            },
        ),
    ]
