# Generated by Django 5.2.9 on 2025-12-21 06:36

from django.db import migrations

def insert_data(apps, schema_editor): # migrate 시 자동 실행
    ShortURL = apps.get_model("shortener", "ShortURL") # 마이그레이션 실행 시점의 모델 스냅샷
    objects = [
        ShortURL(
            original_url = "https://chat.com/",
            code = "ChatGpt"
        ),
        ShortURL(
            original_url = "https://stackoverflow.com/",
            code = "StackOF"
        ),
        ShortURL(
            original_url = "https://github.com/",
            code = "GitHub"
        ),
    ]
    ShortURL.objects.bulk_create( # 세 개의 객체 한 번의 함수 호출로 생성
        objs=objects, ignore_conflicts=True,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'), # 테이블 생성 후 insert
    ]

    operations = [
        migrations.RunPython(
            insert_data,
            reverse_code=migrations.RunPython.noop, # rollback 시 아무것도 안함
        ),
    ]
